spring:
  application:
    name: FraudDetectionDemo
  datasource:
    # MySql 8.0以上版本
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 兼容以前的配置
    jdbc-url: jdbc:mysql://122.9.206.65:3310/fraud?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    url: ${spring.datasource.jdbc-url}
    username: root
    password: root
  mail:
    host: smtp.126.com
    port: 25 # 465
    username: yan_shaohui@126.com
    password: ZLtHBBwS9udziuKp
    protocol: smtp
  redis:
    host: 122.9.206.65
    port: 6379
    timeout: 20000  # 连接超时时间（毫秒）
    database: 0   #Redis数据库索引0-255其中一个，默认0
    jedis:
      pool:
        max-active: 50  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 50  # 连接池中的最大空闲连接
        min-idle: 10  # 连接池中的最小空闲连接
        max-wait: 2000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        time-between-eviction-runs: 60000
  kafka:
    bootstrap-servers: 122.9.206.65:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false
server:
  port: 8088

hsbc:
  email:
    from: yan_shaohui@126.com
    to: 1029588722@qq.com
